### ISSUE TITLE
./test.sh shows some differences

### ISSUE THREAD

**Issue by YanpingHu** [CRISPRlab/CRISPRdisco#6]
After I run ./test.sh,the result shows:
_diff -s test/known_results/CRISPR-Cas_Subtype_summary.csv test/test_output/CRISPR-Cas_Subtype_summary.csv
3c3
< 1,TypeI-B,2
---
> 1,TypeI-B,0
9c9
< 7,TypeII-A,1
---
> 7,TypeII-A,0
diff -s test/known_results/CRISPR-Cas_Type_summary.csv test/test_output/CRISPR-Cas_Type_summary.csv
2,3c2,3
< 0,TypeI,2
< 1,TypeII,1
---
> 0,TypeI,0
> 1,TypeII,0
diff -s test/known_results/CRISPR_repeat_seqs_TEST.csv test/test_output/CRISPR_repeat_seqs_TEST.csv
2,4c2,4
< 0,NC_006449,minced:0.2.0,repeat_unit,625101,627844,42,+,CRISPR1,TTTTTGTACTCTCAAGATTTAAGTAACTGTACAAC
< 0,NC_023011,minced:0.2.0,repeat_unit,98414,99292,14,+,CRISPR1,TTTCAGACGAACCCTCGTGGGGTTGAAGC
< 0,NC_015847,minced:0.2.0,repeat_unit,1030344,1034394,56,-,CRISPR1,GTTTCAATGCTTGTTATTTTGCAAGTTATTCTTTTA
---
> 0,NC_006449,minced:0.2.0,repeat_unit,627809,627844,42,+,CRISPR1,TTTTTGTACTCTCAAGATTTAAGTAACTGTACAAC
> 0,NC_023011,minced:0.2.0,repeat_unit,99263,99292,14,+,CRISPR1,TTTCAGACGAACCCTCGTGGGGTTGAAGC
> 0,NC_015847,minced:0.2.0,repeat_unit,1034358,1034394,56,-,CRISPR1,GTTTCAATGCTTGTTATTTTGCAAGTTATTCTTTTA
Files test/known_results/Genomes_without_CRISPR_TEST.csv and test/test_output/Genomes_without_CRISPR_TEST.csv are identical
Files test/known_results/.gitignore and test/test_output/.gitignore are identical
diff -s test/known_results/Master_CRISPR_summary_table_TEST.csv test/test_output/Master_CRISPR_summary_table_TEST.csv
2,4c2,4
< 0,NC_006449,1.0,6.0,6.0,cas1|cas9|csm6|csn2,TypeII,TypeII-A,1,0,0,
< 1,NC_015847,1.0,4.0,4.0,cas1|cas3|cas4|cas8b,TypeI,TypeI-B,1,0,0,
< 2,NC_023011,1.0,4.0,4.0,cas1|cas3|cas4|cas8b,TypeI,TypeI-B,1,0,0,
---
> 0,NC_006449,1.0,0.0,0.0,0,0,0,0,0,0,
> 1,NC_015847,1.0,0.0,0.0,0,0,0,0,0,0,
> 2,NC_023011,1.0,0.0,0.0,0,0,0,0,0,0,
Files test/known_results/repeat_summary_table_TEST.csv and test/test_output/repeat_summary_table_TEST.csv are identical

I help you help me to solve it.Thanks

**Comment by abriner** [comment]
Hi YanpingHu - It doesn't look like the blast ran. Are you using the program in the docker container or did you install it locally?

If you installed it locally, you need to change the location of the reference data sets in the code and reinstall the program.

**Comment by YanpingHu** [comment]
I install it locally.Because I just started learning it,I don't know what should I do next.Could you tell me how to change the location of the reference data sets in the code.Thanks!

**Comment by abriner** [comment]
See this section on the README.
![Screen Shot 2019-11-11 at 9 25 44 AM](https://user-images.githubusercontent.com/22744430/68594343-54d9f680-0465-11ea-933a-487d6b9e78ed.png)
